spring:
  data:
    cassandra:
      port: 9042
      contact-points: mycassandra
      keyspace-name: mykeyspace
      shema-action: create_if_not_exists
      entitiy-base-package: com.fatihucar.demo.model